### PR TITLE
Add support for creating FixedDecimals from strings

### PR DESCRIPTION
**Pull request by omus**
Allows for precise creation of FixedDecimal values without using a floating point.

Continuation of https://github.com/JuliaFinance/Currencies.jl/pull/77

### CODE REVIEW

**Comment by TotalVerb** [comment]
This is looking good, thanks. However, I think we need to figure out something to do in the case that the string has too much precision. Options are:

- throw InexactError?
- round?
- truncate? (what's being done right now)

With `Floatxx` types, rounding is done instead of `InexactError`. But `FixedDecimal` may have greater appetite for throwing an error here. What do you think?

**Comment by TotalVerb** [comment]
(I added a few tests, some of them skipped while we decide what best to do on extra precision.)

**Comment by omus** [comment]
I think rounding as the default is reasonable as that is what everything else does currently. I may add in a keyword argument to allow the user to select truncation if they prefer.

I like the concept of raising an exception if the string precision is greater than the precision of the FixedDecimal. At the moment however I'm not sure when a user would want this behaviour.

**Comment by omus** [comment]
Supporting rounding resulted in me heavily refactoring the existing parse code. I ended up using `RoundingMode` to allow the user to specify the behaviour they want. Users can use `RoundNearest` (the default), `RoundToZero` (truncate), or the new rounding mode: `RoundThrows`. The new mode will raise an `InexactError` if the provided string cannot be precisely represented in the specified `FixedDecimal` type.

**Pull request merged**
